<Project>
  <PropertyGroup>
    <VcpkgEnableManifest>true</VcpkgEnableManifest>
    <VcpkgManifestRoot>$(MSBuildThisFileDirectory)</VcpkgManifestRoot>
    <VcpkgInstalledDir>$(MSBuildThisFileDirectory)vcpkg_installed</VcpkgInstalledDir>
    <VcpkgRoot>$(MSBuildThisFileDirectory)vcpkg</VcpkgRoot>
    <VcpkgTriplet>x64-windows</VcpkgTriplet>
  </PropertyGroup>
</Project>